---
    # Customer ID and VRF Name must be 31 Characters or less for UCS to accept them.
    Customer_ID: '11021837'
    Customer_VRF: 'Armbrecht-Jackson'

    vlans:
      # SourceFire Inside Vlan. Will be pinned via private vlans to the SF Outside -> ASA Inside interface.
      - id: 1312
        name: SF-Inside
        subnet: '172.17.0.192'
      # Management Network. leaked via VRF tables outside the customer's network. 
      - id: 1712
        name: Mgmt
        subnet: '172.18.0.192'
      # Customer's Transport Network
      - id: 1112 
        name: MPLS
        subnet: '172.16.2.192'

    private_vlans:
      SFInside:
        public: 48 
        private: 47

    private_vlan_interfaces:
        - id: 48
          name: 'ASAInside'
        - id: 48
          name: 'SFOutside'
        
    # Subnet IP Addressing
    Subnet_SF_Inside: '172.17.0.192'
    Subnet_MGMT_Inside: '172.18.0.192'
    Subnet_Transport: '172.16.2.192'
